// <auto-generated />
using InfnetFlix;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfnetFlix.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260317232247_ModificandoTabela")]
    partial class ModificandoTabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.2.26159.112");

            modelBuilder.Entity("InfnetFlix.Models.Perfil", b =>
                {
                    b.Property<int>("idPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("emailLogado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("idadePerfil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isInfantil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomePerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pin")
                        .HasColumnType("TEXT");

                    b.HasKey("idPerfil");

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("InfnetFlix.Models.Progresso", b =>
                {
                    b.Property<int>("idPerfil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idTitulo")
                        .HasColumnType("INTEGER");

                    b.Property<double>("minutoParada")
                        .HasColumnType("REAL");

                    b.HasKey("idPerfil", "idTitulo");

                    b.ToTable("Progressos");
                });

            modelBuilder.Entity("InfnetFlix.Models.Titulo", b =>
                {
                    b.Property<int>("idTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("duracao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idadeMinima")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imagemCapa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeTitulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("qualidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idTitulo");

                    b.ToTable("Titulos");
                });

            modelBuilder.Entity("InfnetFlix.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("emailUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("idadeUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isPremium")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("senhaUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
